projects:
  rgpdayAPI:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: 2mwueq325zbqxiof4v7hry6qmu
      endpoints:
        prod: >-
          https://7zibadpsbbdt7jzhs5ehkamaca.appsync-api.eu-west-1.amazonaws.com/graphql
